### PR TITLE
Integrate golangci-lint

### LINKED ISSUE #21: Integrate GolangCI-Lint
Mattermost is currently in the process of using [`golangci-lint`](https://github.com/golangci/golangci-lint/) as the default linter for all go projects. https://github.com/mattermost/mattermost-plugin-autolink/pull/108 serves as an example of how the migration should look like:
1. Copy `.golangci.yml` from https://github.com/mattermost/mattermost-plugin-autolink/ into this repository.
2. Copy `Makefile` from https://github.com/mattermost/mattermost-plugin-autolink/ into this repository.
3. Copy `build/` from https://github.com/mattermost/mattermost-plugin-autolink/ into this repository.
4. Run `go mod tidy` and `make dist` to ensure the build system works fine.
5. Update `linters-settings.goimports.local-prefixes` to the go module path i.e. to `github.com/mattermost/mattermost-plugin-aws-SNS`.
6. Run `make golangci-lint` and fix all issues that arise.

Fixing an linter issue is sometimes trivial but can also be quite complicated. There might be cases, where ignoring an issue using [`issues.exclude-rules`](https://github.com/golangci/golangci-lint/#config-file) is needed. If you don't know how to resolve an error, please reach out to `@hanzei` on the [Mattermost Community Server](https://community.mattermost.com) or ask the question here.

### PR DESCRIPTION
**Pull request by shihanng**
Close #21.

PR is created based on the steps mentioned in #21.
https://github.com/mattermost/mattermost-plugin-email-reply/issues/21#issue-702044250

Did not get any error from linters.

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @shihanng for the pull request!

cc @hanzei I don't have permission to add reviewers for this PR

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by jasonblais** [comment]
@hanzei @jfrerich can one of you help add `hacktoberfest-accepted` label? Thanks! (I don't have permissions to)

**Review by jfrerich — APPROVED** [review]
Awesome work!  THanks @shihanng!

**Comment by hanzei** [comment]
Tested locally and works fine. Ready to merge!

**Pull request merged**
