### PR TITLE
Don't panic if postID is not found

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Don't panic if postID is not found

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-email-reply/issues/17

### CODE REVIEW

**Comment by hanzei** [comment]
@jprusch Could you please check if this fixes your issue?

**Comment by jprusch** [comment]
Sorry, I'm not a go dev. Could you provide a build for testing?

**Comment by hanzei** [comment]
Unfortunately I can't upload the build on GitHub. Can you please ping me on the [Mattermost Community Server](https://community.mattermost.com)?

**Comment by jprusch** [comment]
Fixed with #19

**Pull request merged**
